'on':
    workflow_dispatch:
        inputs:
            scenario:
                type: choice
                required: true
                options:
                  - Successful product registration with site id
                  - Successful project registration without site id
                  - Successful product registration without Solar Panel without battery without ESS products
                  - Successful product registration without ESS product without battery
                  - Successful product registration without battery
                description: Select a scenario to run
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            name: Checkout code
          - with:
                java-version: '17'
                distribution: temurin
            uses: actions/setup-java@v3
            name: Set up JDK
          - run: mvn clean test -Dcucumber.filter.name="${{ github.event.inputs.scenario }}"
            name: Run Selected Scenario
name: Run Cucumber Tests
