name: Run Cucumber Tests
'on':
  workflow_dispatch:
    inputs:
      scenario:
        type: choice
        description: Select a scenario to run
        options:
        - Successful project registration without site id
        - Successful product registration with site id
        - Successful product registration without Solar panel, ESS product, Warranty
          certificate generation
        - Successful project registration without site id
        - Successful product registration without Solar Panel without battery without
          ESS products
        - Successful product registration without ESS product without battery
        - Successful product registration without battery
        - All
        required: true
jobs:
  run-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v3
    - name: Set up JDK
      uses: actions/setup-java@v3
      with:
        distribution: temurin
        java-version: '17'
    - name: Run Specific Test Case
      env:
        GIT_TOKEN: ${{ secrets.GIT_TOKEN }}
        AIO_TOKEN: ${{ secrets.AIO_TOKEN }}
      if: ${{ github.event.inputs.scenario != 'All' }}
      run: |-
        echo "Running scenario by name: ${{ github.event.inputs.scenario }}"
        export AIO_TOKEN="${{ secrets.AIO_TOKEN }}" && \
        export GIT_TOKEN="${{ secrets.GIT_TOKEN }}" && \
        mvn clean test --no-transfer-progress -q -Dcucumber.filter.name="${{ github.event.inputs.scenario }}"
    - name: Run all tests if no specific scenario is selected
      if: ${{ github.event.inputs.scenario == 'All' }}
      run: |-
        export AIO_TOKEN="${{ secrets.AIO_TOKEN }}" && \
        export GIT_TOKEN="${{ secrets.GIT_TOKEN }}" && \
        mvn clean test --no-transfer-progress -q
