name: Run Cucumber Tests
jobs:
    run-tests:
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - name: Set up JDK
            uses: actions/setup-java@v3
            with:
                java-version: '17'
                distribution: temurin
          - name: Run Selected Scenario
            run: mvn clean test -Dcucumber.filter.name="${{ github.event.inputs.scenario }}"
        runs-on: ubuntu-latest
'on':
    workflow_dispatch:
        inputs:
            scenario:
                type: choice
                description: Select a scenario to run
                options:
                  - Successful product registration with site id
                  - Successful product registration without Solar panel, ESS product, Warranty certificate
                    generation
                  - Successful project registration without site id
                required: true
