name: Run Cucumber Tests
jobs:
    run-tests:
        runs-on: ubuntu-latest
        steps:
          - uses: actions/checkout@v3
            name: Checkout code
          - with:
                distribution: temurin
                java-version: '17'
            name: Set up JDK
            uses: actions/setup-java@v3
          - run: mvn clean test -Dcucumber.filter.name="${{ github.event.inputs.scenario }}"
            name: Run Selected Scenario
'on':
    workflow_dispatch:
        inputs:
            scenario:
                type: choice
                description: Select a scenario to run
                options:
                  - Successful product registration with site id
                  - Successful product registration without Solar panel, ESS product, Warranty certificate
                    generation, and Warranty certificate email send
                  - Successful project registration without site id
                required: true
