'on':
    workflow_dispatch:
        inputs:
            scenario:
                required: true
                options:
                  - Successful product registration with site id
                  - Successful project registration without site id
                description: Select a scenario to run
                type: choice
jobs:
    run-tests:
        steps:
          - name: Checkout code
            uses: actions/checkout@v3
          - uses: actions/setup-java@v3
            name: Set up JDK
            with:
                java-version: '17'
                distribution: temurin
          - name: Run Selected Scenario
            run: mvn clean test -Dcucumber.filter.name="${{ github.event.inputs.scenario }}"
        runs-on: ubuntu-latest
name: Run Cucumber Tests
