name: Send Allure Report Email

on:
  workflow_run:
    workflows: ["Your Workflow Name"]
    types: [completed]

jobs:
  send-email:
    runs-on: ubuntu-latest
    steps:
      - name: Download Allure Report Artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: ${{ github.event.workflow_run.workflow_id }}
          name: allure-report
          path: allure-report

      - name: Send Email
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.example.com
          server_port: 587
          username: qpartnerpoc2305@gmail.com
          password: qpartnerpoc@123
          subject: "Test Report - ${{ github.event.workflow_run.name }}"
          body: "Please find the attached test report."
          to: "client@example.com"
          from: "noreply@example.com"
          attachment: "allure-report/index.html"
          content_type: "text/html"