name: Run Test Cases Manually

on:
  workflow_dispatch 

jobs:
  test_case_1:
    name: Run Test Case 1
    runs-on: macos-latest  
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2

    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'temurin'

    - name: Run Test Case 1
      run: mvn -Dtest=ProductRegistrationSteps test 

  # test_case_2:
  #   name: Run Test Case 2
  #   runs-on: macos-latest  
  #   steps:
  #   - name: Check out repository code
  #     uses: actions/checkout@v2

  #   - name: Set up JDK 17
  #     uses: actions/setup-java@v2
  #     with:
  #       java-version: '17'
  #       distribution: 'temurin'

  #   - name: Run Test Case 2
  #     run: mvn -Dtest=TestClassName2 test # Replace TestClassName2 with your actual test case class name
